### ISSUE TITLE
Feature Request: find_key for YarpDB

### ISSUE THREAD

**Issue by forensicmatt** [msuhanov/yarp#1]
What do you think about constructing a full path table for YarpDB so that a _YarpDB.find_key(path)_ method could be implemented by querying the full path table?

My use case:

I have implemented YarpDB in my tool to use as a possible hive:
https://github.com/forensicmatt/LogicalRegTool/blob/master/lib/RegistryManager.py#L62

But often, I am looking for a specific path to read keys and values. Because of this, I am not always able to use the YarpDB object as a hive, instead, I must use _Registry.RegistryHive_. Here is an example:
https://github.com/forensicmatt/LogicalRegTool/blob/master/lib/plugins/UserAssist.py
```python
user_assist_key = hive.find_key(u'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\UserAssist')
if user_assist_key is not None:
    for guid_key in user_assist_key.subkeys():
           ...
```

This does work. But, it would be nice to just use YarpDB instead of both _RegistrySqlite.YarpDB_ and _Registry.RegistryHive_ .

I could of course iterate through the hive till I find the path I would want, but this would result in lots of overhead queries.

**Comment by msuhanov** [comment]
The problem is that a single key may contain two or more subkeys with the same name: an active one plus one or more deleted subkeys (if any). Thus, there should be a way to resolve possible name conflicts (for example, always prefer an active key).

**Comment by forensicmatt** [comment]
I have also noticed the 
```
if unicode_replacement_character not in curr_name:
    if not self.naive:
        raise WalkException('Duplicate value name, key path: {}, value name: {}'.format(self.path(), curr_name))
    else:
        # Do not build the path, if we are trying to recover a key node.
        raise WalkException('Duplicate value name')
```
 at https://github.com/msuhanov/yarp/blob/master/yarp/Registry.py#L717. 

I tried to use the _iter_ function to try and continue if it happens.

```python
sid_key_values = iter(sid_key.values())
while True:
    try:
        value = next(sid_key_values)
    except StopIteration:
        break
    except Exception as error:
        logging.error(u"Error getting next value: {}".format(error))
        continue
		
	...
```

I would think it would be a good idea to return even duplicated key names, but allow the implementer to do what they want with active vs not? It would be nice to get all of them even if not active.

**Comment by msuhanov** [comment]
> I would think it would be a good idea to return even duplicated key names, but allow the implementer to do what they want with active vs not? It would be nice to get all of them even if not active.

Then it is up to a user of the library to implement the _find_key_ function. Otherwise, the _find_key_ method should return a tree structure to describe all keys found using a given registry path; and, since the caller might want to filter the results, this tree should include information about each key in the path resolved using the method.

_Example:_

The caller asked the library to find the following key: \A\B\C
The following keys were found and returned:
- \A _(active)_\B _(active)_\C _(active)_
- \A _(active)_\B _(active)_\C _(deleted, instance 1)_
- \A _(active)_\B _(active)_\C _(deleted, instance 2)_
- \A _(active)_\B _(deleted, instance 1)_\C _(deleted, instance 1)_

This is an overkill.

**Comment by msuhanov** [comment]
The upcoming release will provide the `subkeys_with_name()` method. Users of the `YarpDB` class may use this method to implement their own `find_key()`-like functionality.

As a side note: the `find_key()` method of the `RegistryHive` class works with active (not deleted) keys only, while the `YarpDB` class works with both active and deleted keys. Hence, implementing a generic `find_key`-like functionality is tricky, because users will not get what they expect in some cases.
